#! /bin/bash

for exe in $1*; do
    name=`basename $exe`
    echo "$name"

    i=0
    while (($i < 10)); do
        for file in $2*.*; do
            outE=`echo ${file%.*}`
            filename=`basename $outE`
            echo -n ", $filename"

            cmd="./$exe < $file"
            exec 3>&1 4>&2
            var=$( { time eval $cmd -args 1>&3 2>&4; } 2>&1 | awk -F'[s.]' '/user/{print $0}')  # Captures time only.
            exec 3>&- 4>&-

            echo -n ", "
            echo $var
        done
        i=$((i + 1))
    done
done